import type { Metadata } from "next";
import localFont from "next/font/local";
import { JetBrains_Mono } from "next/font/google";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, getTranslations, setRequestLocale } from "next-intl/server";
import { SpeedInsights } from "@vercel/speed-insights/next";
import { Analytics } from "@vercel/analytics/next";
import { routing, type Locale } from "@/i18n/routing";
import ServiceWorkerRegistration from "@/components/ServiceWorkerRegistration";

const iaWriter = localFont({
  src: [
    { path: "../../../public/fonts/iAWriterQuattroS-Regular.woff2",    weight: "400", style: "normal" },
    { path: "../../../public/fonts/iAWriterQuattroS-Italic.woff2",     weight: "400", style: "italic" },
    { path: "../../../public/fonts/iAWriterQuattroS-Bold.woff2",       weight: "700", style: "normal" },
    { path: "../../../public/fonts/iAWriterQuattroS-BoldItalic.woff2", weight: "700", style: "italic" },
  ],
  variable: "--font-sans-cng",
  display: "swap",
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-mono-cng",
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://barriosvisibles.ar";

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "metadata" });
  const title = t("title");
  const description = t("description");

  return {
    title,
    description,
    alternates: {
      canonical: `${siteUrl}/${locale}`,
      languages: {
        es: `${siteUrl}/es`,
        en: `${siteUrl}/en`,
        "x-default": `${siteUrl}/es`,
      },
    },
    openGraph: {
      title,
      description,
      url: `${siteUrl}/${locale}`,
      siteName: "Barrios Visibles",
      locale: locale === "es" ? "es_AR" : "en_US",
      alternateLocale: locale === "es" ? "en_US" : "es_AR",
      type: "website",
      // images auto-generated by opengraph-image.tsx
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      // images auto-generated by opengraph-image.tsx
    },
  };
}

export default async function LocaleLayout({ children, params }: Props) {
  const { locale } = await params;

  if (!routing.locales.includes(locale as Locale)) {
    notFound();
  }

  setRequestLocale(locale);
  const messages = await getMessages();

  // JSON-LD structured data
  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: "Barrios Visibles",
    description:
      locale === "es"
        ? "Mapa interactivo de asentamientos informales en Argentina comparando datos oficiales de RENABAP con huellas de edificios detectadas por satélite"
        : "Interactive map of informal settlements in Argentina comparing official RENABAP data with satellite-detected building footprints",
    url: `${siteUrl}/${locale}`,
    applicationCategory: "DataVisualization",
    operatingSystem: "Web",
    inLanguage: locale,
    isAccessibleForFree: true,
    creator: {
      "@type": "Person",
      name: "Nissim Lebovits",
      url: "https://nlebovits.github.io/",
    },
    about: {
      "@type": "Dataset",
      name: "Argentina Informal Settlements Data",
      description: "Comparison of RENABAP official data with Google-Microsoft-OSM building footprints",
      spatialCoverage: {
        "@type": "Place",
        name: "Argentina",
      },
    },
  };

  return (
    <html lang={locale} className={`${iaWriter.variable} ${jetbrainsMono.variable} h-full`}>
      <head>
        {/* Preconnect to tile CDNs for faster map loading */}
        <link rel="preconnect" href="https://server.arcgisonline.com" />
        <link
          rel="preconnect"
          href="https://carbonplan-maps.s3.us-west-2.amazonaws.com"
          crossOrigin="anonymous"
        />
        <link
          rel="preconnect"
          href="https://data.source.coop"
          crossOrigin="anonymous"
        />
        <link rel="dns-prefetch" href="https://nominatim.openstreetmap.org" />
        {/* JSON-LD structured data */}
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
        />
      </head>
      <body className="h-full font-sans">
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
        <ServiceWorkerRegistration />
        <SpeedInsights />
        <Analytics />
      </body>
    </html>
  );
}
